function createhistogram(data1)
%CREATEFIGURE(data1)
%  DATA1:  histogram data

%  Auto-generated by MATLAB on 20-Aug-2019 20:44:33

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create histogram
histogram(data1,'Parent',axes1,'BinMethod','auto');

% Create ylabel
ylabel('N_x');

% Create xlabel
xlabel('x');

% Create title
title('Ãטסעמדנאללא');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 1]);
% Set the remaining axes properties
set(axes1,'FontSize',14,'XGrid','on','YGrid','on');
